### PR TITLE
fix all items when offline synced items less than items per page (#1089)

### PR DESCRIPTION
**Pull request by niol**

### CODE REVIEW

**Comment by jtojnar** [comment]
Can you ask Tobias for commit access? I will not have access to my computer soon and merging from the Web UI does not make for very pretty commit history.

**Comment by niol** [comment]
I'v asked Tobias but I'm not sure what "very pretty commit history" means in that case.

**Comment by jtojnar** [comment]
I mean trying to maintain a linear history using `rebase` command compared to the convoluted graph created by `git merge`.

**Comment by niol** [comment]
I think that as the parent of this pull request commit is the last commit of master, `git merge` won't create a merge commit et rebasing is not needed.

**Comment by jtojnar** [comment]
Yeah, in this case `git merge` would fast forward but the GitHub UI explicitly does not do fast forward merges.

**Comment by SSilence** [comment]
niol I invited you as collaborator

**Pull request merged**
