### PR TITLE
allow windows 8 start screen pinning with notifications

### PR DESCRIPTION
**Pull request by gleroi**
This pull request add the necessary meta tags plus a method to a controller to allow windows 8 to retrieve icon and display the unread count when pinning the site on the start screen.
This should work on windows 8.1 pc/Tablette, and on windows phone 8.1.

### CODE REVIEW

**Comment by bendem** [comment]
Mixed tabs and spaces :disappointed:

**Comment by gleroi** [comment]
updated tab to spaces.

**Comment by bendem** [comment]
:heart:

**Comment by gleroi** [comment]
I added xml as a static resource that can be served from the public folder, by modifying the .htaccess rule.
Not sure if this is ok for your project ?

**Comment by SSilence** [comment]
How can I add a website to my start menue? I have never done this. Waaaa.

**Comment by gleroi** [comment]
From ie11 in moder ui mode, the favorite Burton give the option to save as bookmark or "pinned". Use the pinned option to add it to start screen. 

Guillaume Leroi

-----Message d'origine-----
De : "Tobias Zeising" <notifications@github.com>
Envoyé : ‎08/‎01/‎2015 19:42
À : "SSilence/selfoss" <selfoss@noreply.github.com>
Cc : "Guillaume Leroi" <leroi.g@gmail.com>
Objet : Re: [selfoss] allow windows 8 start screen pinning with notifications(#609)

How can I add a website to my start menue? I have never done this. Waaaa.

**Pull request merged**
