### PR TITLE
Some enhancements on source updating

### PR DESCRIPTION
**Pull request by niol**

### CODE REVIEW

**Comment by niol** [comment]
Is there any problem preventing accepting this PR?

**Comment by SSilence** [comment]
I don't think this is really necessary. It should be the normal usecase that a cronjob updates only 20-30 Minutes. Thanks a lot for this and the many other pull requests!!!

**Comment by niol** [comment]
There were many bug reports related to this. But like you, this is not very useful for my use case.

**Comment by niol** [comment]
If you use the new sync button while the cron script is running, you may get duplicate items
In the db. This PR prevents this.

**Comment by jcbrand** [comment]
> If you use the new sync button while the cron script is running, you may get duplicate items
In the db. This PR prevents this.

That sounds useful.

**Pull request closed without merging**
