### PR TITLE
[WIP] Composer 

### PR DESCRIPTION
**Pull request by jtojnar**
This is still work in progress.

As recommended in #515 I decided to use composer to manage dependencies.

[floIcon](http://www.phpclasses.org/package/3906-PHP-Read-and-write-images-from-ICO-files.html) that was used previously apparently has restrictive license and isn’t available on packagist. jimIcon claims to be a drop-in replacement, it needs to be tested though. I opened [a pull request](https://github.com/jimparis/jimIcon/pull/1) adding composer.json.

We can also get rid of submodules once this [pull request](https://github.com/fivefilters/ftr-site-config/pull/76) gets accepted.

Last remaining libraries not on composer are two FullTextRss components. Where do they come from? It seems like FullTextRss is a [commercial product](http://fivefilters.org/content-only/). For now, I moved them to `vendor/others` directory.

### CODE REVIEW

**Comment by j0k3r** [comment]
For Readability, here is the original from FiveFilters: https://bitbucket.org/fivefilters/php-readability/src (using `fivefilters/php-readability` in your composer).

Otherwise I've forked a fork of that lib which are used in [Wallabag](https://github.com/wallabag/wallabag) project and other one. It's here https://github.com/j0k3r/php-readability

Regarding the ContentExtractor, it's a core part for full-text-rss ([see](https://bitbucket.org/fivefilters/full-text-rss/src/daedf214febe8d944141bb92e2a4c06b8e4a6c12/libraries/content-extractor/?at=master)) you won't be able to get it using composer.

**Comment by niol** [comment]
- Be careful of bugs which were fixed in the selfoss forked libs but not in the original libs. I can think of #636 but there may be more. The diff of the deleted libs vs. the ones pulled from composer should be verified to prevent regressions.
- Please make sure an archive with all deps gets built for releases to make it easy to install selfoss releases

**Comment by jtojnar** [comment]
@j0k3r Bitbucket stopped supporting custom domain names so `fivefilters/php-readability` [can’t be cloned](https://bitbucket.org/fivefilters/php-readability/pull-requests/1) currently. I also like your version better as it has at least some tests.

We could use ContentExtractor from your [Graby](https://github.com/j0k3r/graby), although Graby itself is probably a bit larger than needed. Could the Extractor be extracted to separate composer package? Or maybe selfoss could use Graby instead of SimplePie/ContentExtractor/… combo (another PR perhaps).

@niol that’s why errors should always be fixed upstream :laughing: I will go through https://github.com/SSilence/selfoss/commits/master/libs and try to send pull requests to original libraries if it isn’t fixed in them already. It will have to be verified nevertheless.

I will update Gruntfile later.

**Comment by j0k3r** [comment]
@jtojnar Could be hard to extract. Maybe you should directly use graby instead of ContentExtractor, so you won't need php-readability since it's included in graby.

**Comment by SSilence** [comment]
Thank you for this pr and improvement. I will have a look on composer next time and try to introduce this package manager. I'm not sure this is a good idea for selfoss, because of a few fixes in libraries. floIcon is a little class I copied and I think this should be handled like selfoss source code.

**Comment by jtojnar** [comment]
@SSilence the fixes are already in upstream so that should not be a problem. The reason I did not finish this yet is that I could not find a reasonable way to include the readability filters.

**Comment by Spy-Seth** [comment]
They could be added in a dedicated repository and added as dependence from there. It do not soldve completely the issue but allow to keep moving on this subject.

**Pull request closed without merging**
