### PR TITLE
Allow to collapse/expand filter list

### PR DESCRIPTION
**Pull request by gerundt**
This patch allow to collapse/expand the filter list like the tags and the sources.

### CODE REVIEW

**Comment by jtojnar** [comment]
Looks nice but the utilised area shrinks as the filters are collapsed making the whole thing rather useless.

expand

**Comment by gerundt** [comment]
Mhh, I tested it with Firefox, IE 11 and Android Chrome and have no problems. Which browser use you?

**Comment by jtojnar** [comment]
I tried Firefox and Midori, both exhibit the same behaviour:

https://gfycat.com/ThriftySomberIrishwaterspaniel

**Comment by gerundt** [comment]
Ok, I see the problem now too. I will look to find a solution. Thank you for your hint!

**Comment by gerundt** [comment]
I hope 0873875 fix the problem. Can you try it? :)

**Comment by jtojnar** [comment]
This is more usable but the transition looks horrible. How about moving the filters inside the container with scrollbar?

https://gfycat.com/HomelyWelllitHorsechestnutleafminer

**Comment by gerundt** [comment]
Yes, moving the filters inside the container with the scrollbar could be an option! But I am not sure, if I have enough JavaScript and CSS knowledge for this. :-(

**Comment by jtojnar** [comment]
Hi @gerundt. Previously, it [was not clear](https://github.com/fossar/selfoss/issues/1218) if selfoss was licensed under GPL 3 only, or also any later version. Could you clarify whether you are fine with licensing your contribution under `GPL-3-or-later`?

Thanks again and sorry for the confusion.

**Comment by gerundt** [comment]
Hi, i am fine with GPL 3 or later for all my commits!

**Pull request merged**
