### PR TITLE
Revert 854 revert 834 ppr/navigable

### PR DESCRIPTION
**Pull request by jtojnar**

### CODE REVIEW

**Comment by jtojnar** [comment]
@niol I fixed the sqlite error but there is still one small problem:

1. Select tag containing %
2. Change primary filter

It will raise “Uncaught URIError: URI malformed” both in Firefox and Chrome. It is caused by not urlencoding the writes to `location.hash`. Maybe changing it should be moved to a separate method `updateLocation` that would update the location based on `selfoss.filter`.

**Comment by niol** [comment]
Quick fix:
```diff
--- a/public/js/selfoss-events-navigation.js
+++ b/public/js/selfoss-events-navigation.js
@@ -43,7 +43,7 @@ selfoss.events.navigation = function() {
 
         if( selfoss.events.section != selfoss.filter.type ) {
             location.hash = '#' + selfoss.filter.type
-                            + '/' + selfoss.events.subsection;
+                            + '/' + selfoss.events.subsection.replace('%', '%25');
         }
         
         $('#nav-filter > li').removeClass('active');
```

Regarding factoring out writes to ```location.hash```, I cannot find something elegant.

**Comment by jtojnar** [comment]
@niol okay, now:

1. Select tag containing %
2. Open an item

**Comment by jtojnar** [comment]
It would be best if you could open a new pull request with these changes.

**Comment by niol** [comment]
Can you explain what the expected workflow is? Do you want the same commits or a clean history (i.e. should I squash fix commits) ? Should I cherry-pick your sqlite fix or do you want to add it after? What about my other pull request: do you want only one or should I keep things separate? Should I then rebase?

This will take some time because I do not know how to use composer.

This is a bit discouraging to have to rework all this because of minor bugs that I would have quickly fixed in ```master```.

Anyway I'm testing the following and it seems to behave well.
```diff
diff --git a/public/js/selfoss-base.js b/public/js/selfoss-base.js
index 3f7e16a..35e697c 100644
--- a/public/js/selfoss-base.js
+++ b/public/js/selfoss-base.js
@@ -494,7 +494,7 @@ var selfoss = {
         selfoss.ui.refreshStreamButtons();
 
         // close opened entry and list
-        selfoss.events.processHash(selfoss.events.path);
+        selfoss.events.setHash();
         selfoss.filterReset();
 
         $.ajax({
diff --git a/public/js/selfoss-events-entries.js b/public/js/selfoss-events-entries.js
index 8bd1b9a..1b88963 100644
--- a/public/js/selfoss-events-entries.js
+++ b/public/js/selfoss-events-entries.js
@@ -48,7 +48,7 @@ selfoss.events.entries = function(e) {
             var fullscreen = $('#fullscreen-entry');
             fullscreen.html('<div id="entrr'+parent.attr('data-entry-id')+'" class="entry fullscreen" data-entry-id="'+parent.attr('data-entry-id')+'">'+parent.html()+'</div>');
             fullscreen.show();
-            location.hash = selfoss.events.path + '/' + entryId;
+            selfoss.events.setHash('same', 'same', entryId);
 
             // lazy load images in fullscreen
             if($('#config').data('load_images_on_mobile')=="1") {
@@ -67,7 +67,7 @@ selfoss.events.entries = function(e) {
                     $('#'+parent.attr('id')).hide();
                 }
                 content.show();
-                location.hash = selfoss.events.path;
+                selfoss.events.setHash();
                 $(window).scrollTop(scrollTop);
                 fullscreen.hide();
             });
@@ -84,13 +84,13 @@ selfoss.events.entries = function(e) {
             if(content.is(':visible')) {
                 parent.find('.entry-toolbar').hide();
                 content.hide();
-                location.hash = selfoss.events.path;
+                selfoss.events.setHash();
             } else {
                 if($('#config').data('auto_collapse')=="1"){
                     $('.entry-content, .entry-toolbar').hide();
                 }
                 content.show();
-                location.hash = selfoss.events.path + '/' + entryId;
+                selfoss.events.setHash('same', 'same', entryId);
                 selfoss.events.entriesToolbar(parent);
                 parent.find('.entry-toolbar').show();
                 
@@ -168,7 +168,8 @@ selfoss.events.entries = function(e) {
     if (selfoss.isSmartphone() == false) {
         $('.entry-source').unbind('click').click(function(e) {
             var entry = $(this).parents('.entry');
-            location.hash = '#' + selfoss.filter.type + '/source-' + entry.attr('data-entry-source');
+            selfoss.events.setHash('same',
+                                   'source-' + entry.attr('data-entry-source'));
         });
     }
 
diff --git a/public/js/selfoss-events-navigation.js b/public/js/selfoss-events-navigation.js
index 241a1b3..6dc030e 100644
--- a/public/js/selfoss-events-navigation.js
+++ b/public/js/selfoss-events-navigation.js
@@ -41,11 +41,9 @@ selfoss.events.navigation = function() {
         else if($(this).hasClass('nav-filter-starred'))
             selfoss.filter.type='starred';
 
-        if( selfoss.events.section != selfoss.filter.type ) {
-            location.hash = '#' + selfoss.filter.type
-                            + '/' + selfoss.events.subsection;
-        }
-        
+        if(selfoss.events.section != selfoss.filter.type)
+            selfoss.events.setHash(selfoss.filter.type, 'same');
+
         $('#nav-filter > li').removeClass('active');
         $(this).addClass('active');
         
@@ -71,9 +69,10 @@ selfoss.events.navigation = function() {
         $(this).addClass('active');
         
         if($(this).hasClass('nav-tags-all')==false) {
-            location.hash = '#' + selfoss.filter.type + '/tag-' + $(this).find('span').html().replace('%', '%25');
+            selfoss.events.setHash('same',
+                                   'tag-' + $(this).find('span').html());
         } else {
-            location.hash = '#' + selfoss.filter.type + '/all';
+            selfoss.events.setHash('same', 'all');
         }
             
         if(selfoss.isSmartphone() && $('#nav').is(':visible'))
@@ -95,7 +94,8 @@ selfoss.events.navigation = function() {
         $('#nav-sources > li').removeClass('active');
         $(this).addClass('active');
 
-        location.hash = '#' + selfoss.filter.type + '/source-' + $(this).attr('id').substr(6);
+        selfoss.events.setHash('same',
+                               'source-' + $(this).attr('id').substr(6));
         
         if(selfoss.isSmartphone() && $('#nav').is(':visible'))
             $('#nav-mobile-settings').click();
@@ -194,7 +194,7 @@ selfoss.events.navigation = function() {
         
         // show sources
         $('#nav-settings').unbind('click').click(function () {
-            location.hash = "sources";
+            selfoss.events.setHash('sources');
             
             if(selfoss.isSmartphone())
                 $('#nav-mobile-settings').click();
diff --git a/public/js/selfoss-events-search.js b/public/js/selfoss-events-search.js
index 3134113..5fb1cc6 100644
--- a/public/js/selfoss-events-search.js
+++ b/public/js/selfoss-events-search.js
@@ -38,7 +38,7 @@ selfoss.events.search = function() {
         $('#search').removeClass('active');
         selfoss.filterReset();
         selfoss.filter.search = term;
-        selfoss.events.processHash(selfoss.events.path);
+        selfoss.events.setHash();
         selfoss.reloadList();
         
         if(term=="")
@@ -92,7 +92,7 @@ selfoss.events.search = function() {
         
         selfoss.filterReset();
         selfoss.filter.search = '';
-        selfoss.events.processHash(selfoss.events.path);
+        selfoss.events.setHash();
         $('#search-list').hide();
         $('#search-list').html('');
         $('#search').removeClass('active');
diff --git a/public/js/selfoss-events.js b/public/js/selfoss-events.js
index 9237c7b..ce65aa6 100644
--- a/public/js/selfoss-events.js
+++ b/public/js/selfoss-events.js
@@ -6,7 +6,7 @@ selfoss.events = {
     path:       null,
     lastpath:   null,
     section:    null,
-    subsection: 'all',
+    subsection: false,
     entryId:    null,
 
     /**
@@ -32,7 +32,7 @@ selfoss.events = {
         selfoss.events.resize();
 
         if( location.hash == '' )
-            location.hash = '#' + $('#config').data('homepage') + '/all';
+            selfoss.events.setHash($('#config').data('homepage'), 'all');
         
         // hash change event
         window.onhashchange = selfoss.events.hashChange;
@@ -78,7 +78,7 @@ selfoss.events = {
         if( hashPath.length > 1 ) {
             selfoss.events.subsection = hashPath[1];
         } else
-            selfoss.events.subsection = 'all';
+            selfoss.events.subsection = false;
 
         selfoss.events.lastpath = selfoss.events.path;
         selfoss.events.path = selfoss.events.section
@@ -145,7 +145,24 @@ selfoss.events = {
         done();
     },
     
-    
+
+    setHash: function(section='same', subsection='same', entryId=false) {
+        if( section == 'same' )
+            section = selfoss.events.section;
+        newHash = new Array(section);
+
+        if(subsection == 'same')
+            subsection = selfoss.events.subsection;
+        if(subsection)
+            newHash.push(subsection.replace('%', '%25'));
+
+        if(entryId)
+            newHash.push(entryId);
+
+        selfoss.events.processHash('#' + newHash.join('/'));
+    },
+
+
     /**
      * set automatically the height of the tags and set scrollbar for div scrolling
      */
```

**Comment by jtojnar** [comment]
You can either squash the fix commits or keep them, does not matter to me. Only condition is that pull requests should not contain any discovered bugs. That means SQLite should be fixed in the PR – you can either cherry-pick my fix or fix it in a different way if you have something better in mind.

I would like to focus on this pull request first, #846 should be rebased after this is merged.

As for composer, the only required thing should be calling `composer install`. That will create a vendor directory and download the libraries there.

Yes, sorry about that. Hopefully this will not happen again once we have proper reviews implemented.

**Comment by jtojnar** [comment]
What branch are you applying the patch against? I am not able to apply it?

error: patch failed: public/js/selfoss-base.js:494
error: public/js/selfoss-base.js: patch does not apply

**Pull request closed without merging**
