### PR TITLE
Changed the update url for the refresh button

### PR DESCRIPTION
**Pull request by aminecmi**
It needs to be changed in the "all-v2.13.js" too.

### CODE REVIEW

**Comment by bendem** [comment]
[Update route](https://github.com/SSilence/selfoss/blob/master/index.php#L59) is lower case, what's the reason behind this change?

**Comment by aminecmi** [comment]
The lower case update route returns a 404 error.
I seen on the forum people saying that it was with an upper case U, and it seems to work with theese changes.

**Comment by niol** [comment]
Maybe this is the same as #587 .

**Comment by aminecmi** [comment]
Disabling the MultiViews option didn't elites

**Comment by niol** [comment]
Disabling the MultiViews option solved the same problem for me. What happens if your rename ```update.php```?

**Comment by aminecmi** [comment]
It turns out, Multiviews was enabled for a subdirectory. Changing this resolved the problem.
Can you add theses informations to the main website ?

**Pull request closed without merging**
