### PR TITLE
multi-resolution favicon

### PR DESCRIPTION
**Pull request by mcnesium**
Changed the favicon to include multiple resolutions using the following imagemagick command:

    convert -background transparent icon-128x128.png -define icon:auto-resize=16,32,48,64,128 favicon.ico

The favicon now also looks nice on HiDPI displays.

### CODE REVIEW

**Comment by mcnesium** [comment]
it would be great to have an SVG of the icon to replace the logo.png on the site as well

**Comment by jtojnar** [comment]
Thanks, I will have to ask Tobias about the SVG icon.

**Comment by jtojnar** [comment]
Hi @mcnesium. Previously, it [was not clear](https://github.com/fossar/selfoss/issues/1218) if selfoss was licensed under GPL 3 only, or also any later version. Could you clarify whether you are fine with licensing your contributions here and in other PRs under `GPL-3-or-later`?

Thanks again and sorry for the confusion.

**Comment by mcnesium** [comment]
yes, no problem :+1:

**Pull request merged**
