### PR TITLE
Added Slovak translation

### PR DESCRIPTION
**Pull request by imdyske**

### CODE REVIEW

**Comment by jtojnar** [comment]
Shouldn’t “před” be “pred”?

**Comment by Mychal713** [comment]
Ah, thanks. Totally missed that one.

**Comment by jtojnar** [comment]
Thanks, can you squash it into one commit?

**Comment by Mychal713** [comment]
Sorry I'm new to git. I have no idea how to squash them together.

**Comment by jtojnar** [comment]
That’s all right, this project does not really require a strict coding style. If you want, you can issue `git rebase -i HEAD~2` which will start interactive manipulation with last two commits. Then you can change the second `pick` command to `f` (fixup) and exit the editor. After that you will have to force the changes to github using `git push --force`.

**Comment by Mychal713** [comment]
It's giving me `error: could not apply bd8d286... Added Slovak translation` then I abort the rebase, but no matter which commit I choose to fixup the error is the same.

**Comment by Mychal713** [comment]
Ok, I have managed to resolve the problem. Thanks for your help.

**Comment by jtojnar** [comment]
Hi @imdyske, previously it was not clear if selfoss was licensed under GPL 3 only, or also any later version. Could you clarify whether you are fine with licensing your contribution under `GPL-3-or-later`?

Thanks again and sorry for the confusion.

**Pull request merged**
