### PR TITLE
My queue of various fixes

### PR DESCRIPTION
**Pull request by niol**
Details are in the commit messages.

### CODE REVIEW

**Comment by Alcatr4zz** [comment]
Unfortunately, commit 1849b98 destroys links and line breaks in tweets:

Before:
before

After (not the same tweet):
after

**Comment by niol** [comment]
OK, I understand that the twitter spout uses title for content. This is easy to fix : as I do not have a twitter API key, can you provide me with the elements to allow in the spout title? For your comment, I see ```a``` and ```br```. Are there any others?

**Comment by Alcatr4zz** [comment]
No, there aren't any others, the `a` and `br` elements should be sufficient.

**Comment by Alcatr4zz** [comment]
Thank you. Could you please add the `target` attribute to the allowed ones? This allows links to be opened in a new tab/window.

**Comment by jtojnar** [comment]
Hmm, f49e1ae11b3aa2dac50ebdf32e2dd278b8941cc8 was essentially reverted by 7bb268925698e724432be7c82eeaa384e7856297, while still allowing the width attributes on random tags like tables. Any idea why would @SSilence want to revert it?

**Pull request merged**
