### PR TITLE
Fix dist

### PR DESCRIPTION
**Pull request by jtojnar**
Two regressions from #1137.

Closes: https://github.com/SSilence/selfoss/issues/1144

### CODE REVIEW

**Comment by akash07k** [comment]
So is it merged in master?

**Comment by akash07k** [comment]
O, just checked, it is not merged. I'll apply the patch

**Comment by jtojnar** [comment]
It was merged to master, not sure what you saw.

**Comment by akash07k** [comment]
Ya, realised the same.
Actually there was some problem with my caches. when I cleared and
refreshed the pages, I found it got merged

**Pull request merged**
