### PR TITLE
Added the other android app link to the selfoss website.

### PR DESCRIPTION
**Pull request by aminecmi**

### CODE REVIEW

**Comment by aminecmi** [comment]
Any problem with this PR ?

**Comment by jtojnar** [comment]
Closed as f78be3b5e0b16aeaa3809ac6e725a86d954b1fbc

**Comment by jtojnar** [comment]
Hi @aminecmi. Previously, it [was not clear](https://github.com/fossar/selfoss/issues/1218) if selfoss was licensed under GPL 3 only, or also any later version. Could you clarify whether you are fine with licensing your contributions here and in other PRs under `GPL-3-or-later`?

Thanks again and sorry for the confusion.

**Comment by aminecmi** [comment]
Hi @jtojnar 

I'm completely fine with using `GPL-3-or-later`.

Should I do something for this ? Or this comment is enough ?

**Comment by jtojnar** [comment]
The comment should be sufficient as I understand it, thanks.

**Pull request closed without merging**
