### PR TITLE
Fix read count of secondary tags

### PR DESCRIPTION
**Pull request by jtojnar**
Cherry-picked https://github.com/wazari972/selfoss/commit/3853d6423c3925978119ed0be0171da1611ca5a4, should fix the error reported in #740 (not the issue itself though). It will also make hidden tags actually work as promised in #714.

Problems not fixed in this pull request:
* _Unread_ filter count is subtracted multiple times when a feed has multiple hidden tags (it can even show negative count).
* _Unread_ filter count is not AJAX-updated when you tag/untag a source with a hidden tag.
* Number of unread items below the fold (#747) doesn’t subtract the hidden items.
* Private tags are still displayed in sidebar, although they correctly don’t show any content.
* There is not documentation.

### CODE REVIEW

**Comment by Poorchop** [comment]
Not that it makes a difference, but isn't the indentation off here? Why 8 spaces instead of 4?

**Comment by jtojnar** [comment]
Actually there were even tabs mixed in, I just took the commit from @wazari972’s fork and opened a PR.

I edited the commit so it should match the “coding style” better now.

**Comment by wazari972** [comment]
sorry for the indentation problems, tab+spaces is emacs style :$ I don't know how to tell it to follow the original style !

I don't remember exactly what was the problem solved by that patch, but I use it since I wrote it and secondary tags count work well.

(the only minor problem on the JS side is the -1 on the *main* tag count that should not happened, but I'm too lazy to fix it :- )

**Comment by jtojnar** [comment]
The original code only considered hidden **only** the tag '#'. This change makes it so any tag **containing** '#' is hidden.

I only submitted this pull request to remove `numberOfUnreadForTag` call but making #714 work is a nice bonus.

The negative unread count can happen when a feed has multiple hidden tags (its items are subtracted multiple times). Another (although minor) problem is that the filter (unread) count is not AJAX-updated when you tag/untag a source with a hidden tag. And of course, the missing documentation is also pain. But these can be fixed in a separate PR.

**Comment by PhrozenByte** [comment]
Instead of matching a `@` and `#` anywhere in the string, it would be great to check just the first char - this should avoid accidental matchings.

**Comment by jtojnar** [comment]
@PhrozenByte Yes, I was not sure whether this was intentional. Maybe @wazari972 accidentally used `strcmp` instead of `strpos` and changed it to `strstr` when it did not work.

Now it should only hide tags beginning with '#'.

**Comment by PhrozenByte** [comment]
Great, thanks @jtojnar! Can you please implement this for `@`, too?

**Comment by jtojnar** [comment]
@PhrozenByte this should probably do it.

It is little messy because selfoss stores tags a text. Maybe the `foreach`es could be moved to a separate function, I am not sure where should it go in this though. IMHO this thing whole thing should be handled inside the controllers not in DAOs (if anywhere).

**Comment by jtojnar** [comment]
Also this doesn’t really work well with #747

**Comment by wazari972** [comment]
@jtojnar @PhrozenByte 
> Instead of matching a @ and # anywhere in the string, it would be great to check just the first char - this should avoid accidental matchings.
> Yes, I was not sure whether this was intentional. Maybe @wazari972 accidentally used strcmp instead of strpos and changed it to strstr when it did not work.

if I remember correctly, the problem was that the tags are stored in one string, like "tag, #hidentag, tag, #hidentag...". So checking that # is at position 0 doesn't work. But I can't remember why I didn't look for " #..." instead of deciding that "# can be anywhere in the name" ... (I'm not good at PHP and don't know it's API very well, maybe that's the answer ;-)

**Comment by jtojnar** [comment]
@wazari972 Yes, after trying to change it for `@`, I realised that was probably your reason for not checking position 0. Anyway, in 7bc88f9 it should be handled correctly.

**Pull request merged**
