### PR TITLE
Render sources in navigation client-side

### PR DESCRIPTION
**Pull request by jtojnar**
cc @niol

### CODE REVIEW

**Comment by jtojnar** [comment]
In the future, we can replace this with virtual-dom-based templates (e.g Vue.js); for now, this should not be much worse than the current solution.

**Comment by akash07k** [comment]
Is this PR still in progress? or we can merge it now?

**Comment by jtojnar** [comment]
Yeah, this is WIP. I will revisit it after #1096

**Comment by akash07k** [comment]
Ok, great.

**Comment by jtojnar** [comment]
Surpassed #1184

**Pull request closed without merging**
