### PR TITLE
Fix file permissions

### PR DESCRIPTION
**Pull request by PhrozenByte**
These files shouldn't be executable

### CODE REVIEW

**Comment by martinsauter** [comment]
Yes, they are indeed executable and shouldn't be. Interesting as most other files in those directories have correct file permissions.

**Comment by jtojnar** [comment]
Maybe these files were created on windows and git incorrectly recognized them as executable scripts (the assignments in locales).

**Comment by SSilence** [comment]
Thanks a lot for this pr. I'm on WIndows. Can you fix the merge conflicts? Than I merge this.

**Comment by PhrozenByte** [comment]
I've no idea why GitHub marks this as conflicting... When merging locally everything is just fine. I would suggest to merge the changes locally or cherry-pick the commit.

**Comment by SSilence** [comment]
I merged this manually. Thanks a lot for the pr!

**Pull request closed without merging**
