### PR TITLE
a11y: issues with aria-current on the entry

### PR DESCRIPTION
**Pull request by akash07k**
aria-current has been incorrectly applied to the whole entry instead of only title.
I've temporarily commented both the lines in the selfoss-ui.js which were responsible for this.
It seems that we'll have to do some changes so that aria-current gets applied to the title of the entry only and not to the whole entry.
If it is not possible, then we can skip aria-current for entry all together.

### CODE REVIEW

**Comment by jtojnar** [comment]
Hmm, those lines should read `selfoss.ui.selectedEntry.find('.entry-title > .entry-title-link').attr('aria-current', …);`. Could you please change it to that and rebase the whole branch onto `master`?

**Comment by akash07k** [comment]
> Hmm, those lines should read `selfoss.ui.selectedEntry.find('.entry-title > .entry-title-link').attr('aria-current', …);`. Could you please change it to that and rebase the whole branch onto `master`?

The branch is already rebased to the master. I tried again, but it is saying that everything is up to date. done the changes, working fine, but don't know that why the checks are failing now

**Comment by jtojnar** [comment]
Are you rebasing against the current `git@github.com:SSilence/selfoss.git` master?

**Comment by akash07k** [comment]
Yes

**Comment by akash07k** [comment]
Although I've rebased against the master branch of SSilence/selfoss.git, but still, it is wshowing that "you are 81 commits ahead" pulling and pushing does nothing.

**Comment by jtojnar** [comment]
Hmm, for me the rebase fails with a conflict. I would suggest [`git rebase --interactive`](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history) and dropping all old commits.

**Comment by akash07k** [comment]
Ok, will try that. and if it doesn't work, then I'll delete my fork
and will refork it again.

**Comment by akash07k** [comment]
Closing due to the conflicts. Going to create the new pull request as all the conflicts are now resolved and the rebasing is done in a proper way

**Pull request closed without merging**
